config/routes.rb
Rails.application.routes.draw do
  root "photos#index"
  
  resources :photos do
    member do
      post :is_public
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :file_location, PhotoImageUploader
  validates_presence_of :title, :date, :description, :file_location
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy, :is_public]

  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      redirect_to photos_path
      flash[:notice] = 'aaaaa'
    else
      flash.now[:notice] = 'bbbbb'
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @photo.update(photo_params)
      redirect_to photo_url(@photo)
    else
      render :edit
    end
  end

  def destroy
    @photo.destroy
    redirect_to photos_path
  end

  def is_public
    @photo.update(is_public: !(@photo.is_public))
  end

  private

  def set_photo
    @photo = Photo.find(params[:id])
  end

  def photo_params
    params.require(:photo).permit(:title, :date, :description, :file_location)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoAlbum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= puts flash[:notice] %>
    <div class="container">
      <% if flash[:notice].present? %>
        <div class="alert alert-success" role="alert">
          <%= flash[:notice] %>
        </div>
      <% end %>


      <% if flash[:alert].present? %>
        <div class="alert alert-danger" role="alert">
          <%= flash[:alert] %>
        </div> 
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/photos/_form.html.erb
<div class="container text-success">
  <% if @photo.errors.present? %>
    <%= link_to 'aaa', '/', class: 'text-success' %>
    <ul>
      <% @photo.errors.each do |error, message| %>
        <li><%= "#{error.capitalize} #{message}" %></li>
      <% end %>
    </ul>
  <% end %>

  <%= form_for @photo do |f| %>
    <div class="form-group">
      <%= f.label :title, "Title" %>
      <%= f.text_field :title, class: "form-control" %>  
    </div>
    
    <div class="form-group">
      <%= f.label :date, "Date" %>
      <%= f.text_field :date, class: "form-control" %>  
    </div>
    
    <div class="form-group">
      <%= f.label :description, "Description" %>
      <%= f.text_field :description, class: "form-control" %>
    </div>
      
    <div class="form-group">
      <%= f.label :file_location, "File Location" %>
      <%= f.file_field :file_location %>
    </div>
      
    <div class="form-group">
      <% unless @photo.new_record? %>
        <%= image_tag @photo.file_location.url %>  
      <% end %>
    </div>
    
    <div class="form-actions">
      <%= f.submit %>  
    </div>
  <% end %>
</div>
  

app/views/photos/edit.html.erb
<%= render "form" %>

app/views/photos/index.html.erb
<div class="container">
  <table class="table table-striped table-condensed">
    <tr>
      <th>is_public</th>
      <th>Title</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>

    <% @photos.each do |photo| %>
      <tr>
        <td>
          <%= check_box_tag :is_public, true , photo.is_public, data: { url: is_public_photo_path(photo), method: :post, remote: true } %>
        </td>
        <td><%= photo.title %>
        <td><%= link_to "Show", photo_path(photo) %>
        <td><%= link_to "Edit", edit_photo_path(photo) %>
        <td><%= link_to "Destroy", photo_path(photo) , method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </table>

  <%= link_to "New Photo", 'photos/new' %>
</div>
  

app/views/photos/new.html.erb
<%= render "form" %>

app/views/photos/show.html.erb
<%= @photo.title %>
<%= @photo.date %>
<%= image_tag @photo.file_location.url, size: "140x140", class: "img-thumbnail" %>
<%= simple_format(@photo.description) %>

<%= link_to "Back to index", photos_path %>